### ISSUE TITLE
throttle.exceptions.RateLimitExceeded: default

### ISSUE THREAD

**Issue by alimp5** [sobotklp/django-throttle-requests#23]
When we reached to limit. your app tries to show a 403 forbidden page.

I'm using default configs.

```
Forbidden (Permission denied): /books/hello/
Traceback (most recent call last):
  File "C:\Users\linux10\Desktop\my_all_envs\azimzadeh_env1\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\linux10\Desktop\my_all_envs\azimzadeh_env1\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\linux10\Desktop\my_all_envs\azimzadeh_env1\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\linux10\Desktop\my_all_envs\azimzadeh_env1\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\linux10\Desktop\my_all_envs\azimzadeh_env1\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\linux10\Desktop\my_all_envs\azimzadeh_env1\lib\site-packages\throttle\decorators.py", line 15, in _wrapped_view
    response = _throttle_zone.process_view(request, func, args, kwargs)
  File "C:\Users\linux10\Desktop\my_all_envs\azimzadeh_env1\lib\site-packages\throttle\zones\__init__.py", line 72, in process_view
    raise RateLimitExceeded(self.name)
throttle.exceptions.RateLimitExceeded: default
[16/May/2021 15:54:03] "GET /books/hello/ HTTP/1.1" 403 200
```

**Comment by alimp5** [comment]
I edited `__init__.py` file in `zones` directory:
and now it's works without Traceback error.

```
# Has the bucket capacity been exceeded?
if new_value > self.bucket_capacity:
      #raise RateLimitExceeded(self.name)
      return HttpResponse ("<h4>Django test response</h4>")
```

**Comment by pryelluw** [comment]
@alimp5 Wouldn't it be simpler to catch the exception in your code?

```
try:
    return HttpResponse ("<h4>Django test response</h4>")

except RateLimitingExceeded:
      content = {'message': 'eeeeeeeeeeeeeeeee'}
      return HttpResponse (json.dumps(content), status=429, content_type="application/json")
```

**Comment by sobotklp** [comment]
@alimp5 This is actually expected behaviour since `RateLimitExceeded` inherits from `PermissionDenied`:

    from django.core.exceptions import ImproperlyConfigured, PermissionDenied

    class RateLimitExceeded(PermissionDenied):
        pass

I'm considering changing that so the default HTTP return code is 429 Too Many Requests.
